apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: backend
  template:
    metadata:
      labels:
        app: backend
        tier: backend
    spec:
      containers:
      - name: "edge-node-redis-shopping-backend"
        image: backend:0.1
        ports:
        - name: http-server
          containerPort: 3000
        env:
        - name: NODE_ENV
          value: production
        - name: PORT
          value: "4000"
        - name: DB_HOST
          value: "localhost"
        #   value: "example-client.redis.svc.cluster.local:6379"
        - name: DB_PORT
          value: "6379"
