apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
    tier: backend
spec:
  type: NodePort
  selector:
    app: backend
    tier: backend
  ports:
  - port: 4000
    targetPort: http-server
    nodePort: 30200
    name: http-server
